version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/linux/Dockerfile
      cache_from:
        - ghcr.io/kaidokert/chromium/linux:latest
    image: ghcr.io/kaidokert/chromium/linux:latest
    platform: linux/amd64
    environment:
      - DEPOT_TOOLS_UPDATE=0
