name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest-m # Larger Runner with 150gb ssd
    container: ghcr.io/kaidokert-personal-org/chromium/linux:mod2
    env:
      SCCACHE_GCS_KEY: ${{ secrets.SCCACHE_GCS_KEY }}

    steps:
      - name: Place sccache key
        run: echo "$SCCACHE_GCS_KEY" | base64 -d > /root/key.json
      - name: Cat the key
        run: cat /root/key.json
      - name: sccache check
        run: sccache -s
      - name: Make file
        run: echo "#include <stdio.h>" > test.cc
      - name: sccache check again
        run: sccache -s
      - name: apt update
        run: apt update
      - name: apt install g++
        run: apt -qqy install g++
      - name: compile a file
        run: sccache g++ -c test.cc
      - name: sccache check again
        run: sccache -s
